<?php

namespace AppBundle\Repository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductosPorPaginacion($pagina, $numeroProductos)
    {
        $query = $this->createQueryBuilder('p')
            //->where('p.id > :id')
            ->orderBy('p.nombre', 'ASC')
            ->setFirstResult($numeroProductos * ($pagina - 1))
            ->setMaxResults($numeroProductos)
            ->getQuery();
        //$query->setParameter('id', 1);
        return $query->getResult();

    }
}
